### PR TITLE
Go With MongoDB

### PR DESCRIPTION
**Pull request by vfarcic**

### CODE REVIEW

**Comment by jstrachan** [comment]
@vfarcic fancy adding a quickstart too to this repo: https://github.com/jenkins-x-quickstarts

**Comment by jstrachan** [comment]
@vfarcic or if you have one already we could just fork it there

**Comment by vfarcic** [comment]
Will do :)

**Comment by vfarcic** [comment]
A side question... What is the difference between this one and that one?

**Pull request merged**
